// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECT.Models;

namespace PROJECT.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190623173117_initDB")]
    partial class initDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("PROJECT.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CargoSpace");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<int>("GasMileage");

                    b.Property<int>("HP");

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<int>("Passengers");

                    b.Property<string>("Picture");

                    b.Property<string>("RentPrice");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("PROJECT.Models.Representative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Representative");
                });
#pragma warning restore 612, 618
        }
    }
}
